INCORRECT_PASSWORD_ERROR = 101
USER_NOT_FOUND_ERROR = 102
EXISTED_LOGIN_ERROR = 103
ACCOUNT_NUMBER_ERROR = 111
ZERO_OPERATION_ERROR = 112
INCORRECT_ACCOUNT_TYPE_ERROR = 113
INSUFFICIENT_FUND_WITHDRAW_ERROR = 301
INSUFFICIENT_FUND_TRANSFER_ERROR = 302
VALIDITY_PERIOD_ERROR = 311
WITHDEAWAL_LIMIT_ERROR = 312
LIMITED_ACCOUNT_TRANSFER_ERROR = 412
LIMITED_ACCOUNT_WITHDRAW_ERROR = 413
INCORRECT_ACCOUNT_ID_ERROR = 404


EX_CODE_MESSAGES = {
    INCORRECT_PASSWORD_ERROR: "incorrect password",
    USER_NOT_FOUND_ERROR: "user not found",
    EXISTED_LOGIN_ERROR: "login is already existed",
    ACCOUNT_NUMBER_ERROR: "unavailable account number",
    ZERO_OPERATION_ERROR: "amount should be upper than 0",
    INCORRECT_ACCOUNT_TYPE_ERROR: "unavailable account type",
    INSUFFICIENT_FUND_WITHDRAW_ERROR: "insufficient funds to withdraw",
    INSUFFICIENT_FUND_TRANSFER_ERROR: "insufficient funds for the transfer",
    VALIDITY_PERIOD_ERROR: "validity_period is not finished",
    WITHDEAWAL_LIMIT_ERROR: "withdrawal limit exceeded",
    LIMITED_ACCOUNT_TRANSFER_ERROR: "limited account. transfer limit exceeded",
    LIMITED_ACCOUNT_WITHDRAW_ERROR: "limited account. withdraw limit exceeded",
    INCORRECT_ACCOUNT_ID_ERROR: "non-existent account id"
    }
